using Domain.Interfaces;
using Shouldly;
using System.Diagnostics.CodeAnalysis;
using Xunit;

namespace Tests.Day7;

[ExcludeFromCodeCoverage]
public class WhenGivenInput
{
    private readonly IDay7 _sut = new Domain.Implementations.Day7();
    private const string Input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """;
    private readonly int Expected = 21;

    [Fact]
    public void ThenExpectedOutcome()
    {
        var result = _sut.ParseAndProcess(Input);

        result.ShouldBe(Expected);
    }
}